version: 1

formatters:
  simple:
    format: "%(asctime)s %(levelname)-8s %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  file_handler:
    class: logging.FileHandler
    # level: DEBUG
    formatter: simple
    filename: output.log
    mode: w
    encoding: utf-8

loggers:
  dev:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: no
  test:
    level: DEBUG
    handlers: [file_handler]
    propagate: no

root:
  # level: INFO
  handlers: [file_handler]
